apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-train-deployment-cornell-bert
  labels:
    app: sentiment-train-app-cornell-bert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-train-app-cornell-bert
  template:
    metadata:
      labels:
        app: sentiment-train-app-cornell-bert
    spec:
        containers:
        - name: myapp-container-cornell-bert
          image: mahamarif/sentiment-analysis-cornell-bert
          command: ['bash', '-c', 'python train_bert.py && tail -f /dev/null']
