apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-train-deployment-cornell-cnn
  labels:
    app: sentiment-train-app-cornell-cnn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-train-app-cornell-cnn
  template:
    metadata:
      labels:
        app: sentiment-train-app-cornell-cnn
    spec:
        containers:
        - name: myapp-container-cornell-cnn
          image: mahamarif/sentiment-analysis-cornell-cnn
          command: ['bash', '-c', 'python train_cnn.py && tail -f /dev/null']
