apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-train-deployment-cornell
  labels:
    app: sentiment-train-app-cornell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-train-app-cornell
  template:
    metadata:
      labels:
        app: sentiment-train-app-cornell
    spec:
        containers:
        - name: myapp-container-cornell
          image: mahamarif/sentiment-analysis-cornell-lstm
          command: ['bash', '-c', 'python train.py && tail -f /dev/null']
